export const SSN_INVALID_ADDRESS = 'INVALID_ADDRESS';
export const SSN_PENDING_SIGNATURE = 'PENDING_SIGNATURE';
export const SSN_PENDING_QUESTIONNAIRE = 'PENDING_QUESTIONNAIRE';
export const SSN_PENDING_VALIDATION = 'PENDING_VALIDATION';
export const SSN_PROCESSING_SHIPMENT = 'PROCESSING_SHIPMENT';
export const SSN_COMPLETE = 'COMPLETE';

