export const EDIT_INFORMATION = "EDIT_INFORMATION";
export const REGENERATE_FORM = "REGENERATE_FORM";
export const REGENERATE_PACKAGE = "REGENERATE_PACKAGE";
export const REGENERATE_LABELS = "REGENERATE_LABELS";
export const DOWNLOAD_FORM = "DOWNLOAD_FORM";
export const SEND_STATUS_EMAIL = "SEND_STATUS_EMAIL";

export const CONFIRM = "CONFIRM";

